src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Chat $chat = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $message = null;

    #[Gedmo\Timestampable(on: 'create')]
    #[ORM\Column]
    private ?\DateTimeImmutable $sent_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $reply = null;

    #[Gedmo\Timestampable(on: 'change', field: ['reply'])]
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $replied_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChat(): ?Chat
    {
        return $this->chat;
    }

    public function setChat(?Chat $chat): static
    {
        $this->chat = $chat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getSentAt(): ?\DateTimeImmutable
    {
        return $this->sent_at;
    }

    public function setSentAt(\DateTimeImmutable $sent_at): static
    {
        $this->sent_at = $sent_at;

        return $this;
    }

    public function __toString()
    {
        return $this->message;
    }

    public function getReply(): ?string
    {
        return $this->reply;
    }

    public function setReply(?string $reply): static
    {
        $this->reply = $reply;

        return $this;
    }

    public function getRepliedAt(): ?\DateTimeImmutable
    {
        return $this->replied_at;
    }

    public function setRepliedAt(?\DateTimeImmutable $replied_at): static
    {
        $this->replied_at = $replied_at;

        return $this;
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;
use App\Entity\Chat;
use App\Entity\Message;
use App\Form\MessageFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;

class MessageController extends AbstractController
{
    private $em;
    private $security;

    public function __construct(EntityManagerInterface $em, Security $security)
    {
        $this->em = $em;
        $this->security = $security;
    }

    #[Route('/messages', name: 'app_messages')]
    public function index(Request $request): Response
    {
        $user = $this->security->getUser();
        $userChat = $user->getChat();
        $messages = $user->getMessages();

        if ($userChat == null) {
            $userChat = new Chat();
            $userChat->setCustomer($user);
            $userChat->setCustomerUsername($user->getUsername());
            $this->em->persist($userChat);
            $this->em->flush();
        };

        $newMessage = new Message();
        $newMessage
            ->setChat($userChat)
            ->setUser($user);

        $form = $this->createForm(MessageFormType::class, $newMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formMessage = $form->getData();
            
            $this->em->persist($formMessage);
            $this->em->flush();

            return $this->redirect($request->getUri());
        }

        return $this->render('messages/index.html.twig', [
            'messages' => $messages,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;
use App\Entity\Chat;
use App\Entity\Message;
use App\Form\MessageFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;

class MessagesController extends AbstractController
{
    private $em;
    private $security;

    public function __construct(EntityManagerInterface $em, Security $security)
    {
        $this->em = $em;
        $this->security = $security;
    }

    #[Route('/messages', name: 'app_messages')]
    public function index(Request $request): Response
    {
        $user = $this->security->getUser();
        $userChat = $user->getChat();
        $messages = $user->getMessages();

        if ($userChat == null) {
            $userChat = new Chat();
            $userChat->setCustomer($user);
            $this->em->persist($userChat);
            $this->em->flush();
        };

        $newMessage = new Message();
        $newMessage
            ->setChat($userChat)
            ->setUser($user);

        $form = $this->createForm(MessageFormType::class, $newMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formMessage = $form->getData();
            
            $this->em->persist($formMessage);
            $this->em->flush();

            return $this->redirect($request->getUri());
        }

        return $this->render('messages/index.html.twig', [
            'messages' => $messages,
            'form' => $form->createView()
        ]);
    }
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages{% endblock %}

{% block body %}
    {% include 'partials/nav.html.twig' %}

    <!-- CANVAS -->
    <section class="canvas content">
        <h1>Messages</h1>
    </section>
    <!-- CANVAS END -->

    <!-- MAIN -->
    <main>
        {% if messages|length > 0 %}
            <h2>Continue your conversation</h2>
            {% for message in messages %}
                <div class="user-message">
                    <p><span class="message-time">{{ message.sentAt|format_datetime('none', 'short') }} </span>{{ message.message }}</p>
                    {% if message.reply %}
                        <p class="reply">{{ message.reply }} <span class="message-time">{{ message.repliedAt|format_datetime('none', 'short') }}</span></p>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            <h2>Begin a conversation</h2>
        {% endif %}
        {{ form_start(form) }}
            <div class="security-form full-width">
                <div class="form-row alt-flex">
                    {{ form_row(form.message) }}
                    <button type="submit" class="security-button">
                        <svg width="30px" height="30px" viewBox="0 -0.5 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M18.455 9.8834L7.063 4.1434C6.76535 3.96928 6.40109 3.95274 6.08888 4.09916C5.77667 4.24558 5.55647 4.53621 5.5 4.8764C5.5039 4.98942 5.53114 5.10041 5.58 5.2024L7.749 10.4424C7.85786 10.7903 7.91711 11.1519 7.925 11.5164C7.91714 11.8809 7.85789 12.2425 7.749 12.5904L5.58 17.8304C5.53114 17.9324 5.5039 18.0434 5.5 18.1564C5.55687 18.4961 5.77703 18.7862 6.0889 18.9323C6.40078 19.0785 6.76456 19.062 7.062 18.8884L18.455 13.1484C19.0903 12.8533 19.4967 12.2164 19.4967 11.5159C19.4967 10.8154 19.0903 10.1785 18.455 9.8834V9.8834Z" stroke="#FFFFFF" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </button>
                </div>
            </div>
        {{ form_end(form) }}
    </main>
    <!-- MAIN END -->
{% endblock %}