src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    const TYPE_CART = 'Cart';
    const TYPE_PAID = 'Paid';
    const TYPE_DELIVERED = 'Delivered';
    const TYPE_CANCELLED = 'Cancelled';
    
    const TYPE_ENUM = [
        self::TYPE_CART,
        self::TYPE_PAID,
        self::TYPE_DELIVERED,
        self::TYPE_CANCELLED
    ];

    public static function getStatusSelection(): array
    {
        return array_combine( array_map(static function($enum) {
            return "$enum";
        }, self::TYPE_ENUM), self::TYPE_ENUM);
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $deliveryAddress = null;

    #[Gedmo\Timestampable(on: 'create')]
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $ordered_on = null;

    #[ORM\Column(length: 255, columnDefinition: "ENUM('Cart', 'Paid', 'Delivered', 'Cancelled')")]
    private ?string $status = null;

    #[ORM\OneToMany(mappedBy: 'orderProduct', targetEntity: OrderDetails::class, orphanRemoval: true)]
    private Collection $orderDetails;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paypalId = null;

    #[ORM\Column]
    private ?float $total = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDeliveryAddress(): ?string
    {
        return $this->deliveryAddress;
    }

    public function setDeliveryAddress(string $deliveryAddress): static
    {
        $this->deliveryAddress = $deliveryAddress;

        return $this;
    }

    public function getOrderedOn(): ?\DateTimeInterface
    {
        return $this->ordered_on;
    }

    public function setOrderedOn(\DateTimeInterface $ordered_on): static
    {
        $this->ordered_on = $ordered_on;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetails>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setOrderProduct($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrderProduct() === $this) {
                $orderDetail->setOrderProduct(null);
            }
        }

        return $this;
    }

    public function getPaypalId(): ?string
    {
        return $this->paypalId;
    }

    public function setPaypalId(?string $paypalId): static
    {
        $this->paypalId = $paypalId;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): static
    {
        $this->total = $total;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\OrderDetails;
use App\Entity\Product;
use App\Form\OrderFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Service\CartService;
use Doctrine\ORM\EntityManagerInterface;
use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
use PayPalCheckoutSdk\Orders\OrdersCreateRequest;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


class OrderController extends AbstractController
{
    private EntityManagerInterface $em;
    private UrlGeneratorInterface $urlGenerator;

    public function __construct(EntityManagerInterface $em, UrlGeneratorInterface $urlGenerator)
    {
        $this->em = $em;
        $this->urlGenerator = $urlGenerator;
    }

    #[Route('/order', name: 'app_order')]
    public function index(CartService $cartService, Request $request): Response
    {
        $user = $this->getUser();
        $userAddress = $user->getAddress();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        if(!$user->getAddress()) {
            return $this->redirectToRoute('app_account', [
                'username' => $user->getUsername()
            ]);
        }

        if (count($cartService->getTotal()) < 1) {
            return $this->redirectToRoute('app_products');
        }

        $deliveryAddress = $userAddress->getZipCode() . ', ' . $userAddress->getStreet() . ', ' . $userAddress->getCity() . ', ' . $userAddress->getCountry();
        $total = 0;

        foreach ($cartService->getTotal() as $item) {
            $itemTotal = $item['product']->getPrice() * $item['quantity'];
            $total += $itemTotal;
        }

        $order = new Order();
        $order->setUser($user);
        $order->setReference(uniqid());
        $order->setDeliveryAddress($deliveryAddress);
        $order->setStatus('Cart');
        $order->setTotal($total);

        $this->em->persist($order);

        $form = $this->createForm(OrderFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($cartService->getTotal() as $item) {
                $orderDetails = new OrderDetails();
                $orderDetails->setOrderProduct($order);
                $orderDetails->setQuantity($item['quantity']);
                $orderDetails->setPrice($item['product']->getPrice());
                $orderDetails->setProduct($item['product']->getTitle());
                $orderDetails->setTotalPrice($item['product']->getPrice() * $item['quantity']);

                $this->em->persist($orderDetails);
            }

            $this->em->flush();

            return $this->redirectToRoute('app_payment', [
                'reference' => $order->getReference()
            ]);
        }

        return $this->render('order/index.html.twig', [
            'cart' => $cartService->getTotal(),
            'address' => $userAddress,
            'form' => $form->createView()
        ]);
    }

    public function getPaypalClient(): PayPalHttpClient
    {
        $clientId = 'ARjJ6CVymMw9lFXjvh4vBcP1CNyLmVT0u1o3sUzB40KQMPuYemVTHFIufreRzRqP2x7R9xWgwa8nCXBu';
        $clientSecret = 'ELHDQywJOST3nfE1mQexI7vk6EODBZDj12HR2yCMo0wfGAdjrgJT0nLESLSn-tAFDv-Cd4e4vY-l-NrC';
        $environment = new SandboxEnvironment($clientId, $clientSecret);

        return new PayPalHttpClient($environment);
    }

    #[Route('/payment/{reference}', name: 'app_payment')]
    public function createPaypalSession(string $reference): RedirectResponse
    {
        $order = $this->em->getRepository(Order::class)->findOneBy(['reference' => $reference]);

        if (!$order) {
            return $this->redirectToRoute('app_cart');
        }

        $items = [];
        $itemTotal = 0;

        foreach ($order->getOrderDetails()->getValues() as $product) {
            $items[] = [
                'name' => $product->getProduct(),
                'quantity' => $product->getQuantity(),
                'unit_amount' => [
                    'value' => strval($product->getPrice() / 100),
                    'currency_code' => 'USD'
                ]
            ];

            $itemTotal += ($product->getPrice() / 100) * $product->getQuantity();
        }

        $customer = $order->getUser();
        $customerAddress = $customer->getAddress();
        $customerFirstName = $customerAddress->getFirstName();
        $customerLastName = $customerAddress->getLastName();
        $customerStreet = $customerAddress->getStreet();
        $customerCity = $customerAddress->getCity();
        $customerZipCode = $customerAddress->getZipCode();
        $customerCountry = $customerAddress->getCountry();

        $request = new OrdersCreateRequest();
        $request->prefer('return=representation');
        $paypalBody = [
            'intent' => 'CAPTURE',
            'purchase_units' => [
                [
                    'amount' => [
                        'currency_code' => 'USD',
                        'value' => strval($itemTotal),
                        'breakdown' => [
                            'item_total' => [
                                'currency_code' => 'USD',
                                'value' => strval($itemTotal),
                            ],
                            'shipping' => [
                                'name' => [
                                    'given_name' => $customerFirstName,
                                    'surname' => $customerLastName,
                                ],
                                'address' => [
                                    'address_line_1' => $customerStreet,
                                    'admin_area_1' => $customerCity,
                                    'postal_code' => $customerZipCode,
                                    'country_code' => $customerCountry,
                                ],
                                'currency_code' => 'USD',
                                'value' => 0,
                            ]
                        ]
                    ],
                    'items' => $items
                ]
            ],
            'application_context' => [
                'shipping_preference' => 'NO_SHIPPING',
                'return_url' => $this->urlGenerator->generate('payment_success', ['reference' => $order->getReference()], UrlGeneratorInterface::ABSOLUTE_URL),
                'cancel_url' => $this->urlGenerator->generate('payment_failed', ['reference' => $order->getReference()], UrlGeneratorInterface::ABSOLUTE_URL)
            ]
        ];

        $request->body = $paypalBody;

        $client = $this->getPaypalClient();
        $response = $client->execute($request);

        if ($response->statusCode != 201) {
            return $this->redirectToRoute('app_order');
        }

        $approvalLink = '';

        foreach ($response->result->links as $link) {
            if ($link->rel === 'approve') {
                $approvalLink = $link->href;
                break;
            }
        }

        if (empty($approvalLink)) {
            return $this->redirectToRoute('app_order');
        }
        

        $order->setPaypalId($response->result->id);

        $this->em->flush();

        return new RedirectResponse($approvalLink);
    }

    #[Route('/payment/success/{reference}', name: 'payment_success')]
    public function paymentSuccess(string $reference, CartService $cartService)
    {
        $order = $this->em->getRepository(Order::class)->findOneBy(['reference' => $reference]);

        if (!$order || $order->getUser() !== $this->getUser()) {
            return $this->redirectToRoute('app_cart');
        }

        $order->setStatus('Paid');
        $orderDetails = $order->getOrderDetails();

        foreach ($orderDetails as $item) {
            $product = $this->em->getRepository(Product::class)->findOneBy(['title' => $item->getProduct()]);
            $productStock = $product->getStock();
            $product->setStock($productStock - $item->getQuantity());

            $this->em->persist($product);
        }

        $cartService->clearCart();

        $this->em->flush();

        return $this->render('order/success.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/payment/failed/{reference}', name: 'payment_failed')]
    public function paymentFailed(string $reference)
    {
        $order = $this->em->getRepository(Order::class)->findOneBy(['reference' => $reference]);

        if (!$order || $order->getUser() !== $this->getUser()) {
            return $this->redirectToRoute('app_cart');
        }

        $order->setStatus('Cancelled');

        $this->em->flush();

        return $this->render('order/failed.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/orders', name: 'app_orders')]
    public function userOrders()
    {
        $user = $this->getUser();
        $userOrders = $user->getOrders();

        return $this->render('order/orders.html.twig', [
            'orders' => $userOrders
        ]);
    }
}

templates/order/failed.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    {% include 'partials/nav.html.twig' %}
    <!-- CANVAS -->
    <section class="canvas content">
        <h1>Order</h1>
    </section>
    <!-- CANVAS END -->

    <!-- MAIN -->
    <main>
        <div class="message-button">
            <h2 class="order-number">There was a problem processing your order number <span>{{ order.reference }}</span>.</h2>
            <a href="{{ path('app_payment', { 'reference': order.reference }) }}" class="cart-button">Try again</a>
        </div>
    </main>
    <!-- MAIN END -->
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    {% include 'partials/nav.html.twig' %}
    <!-- CANVAS -->
    <section class="canvas content">
        <h1>Order</h1>
    </section>
    <!-- CANVAS END -->

    <!-- MAIN -->
    <main>
        {{ form_start(form) }}
            <h2>Your information</h2>
            <p class="order-information"><span>Name: </span>{{ address.firstName }} {{ address.lastName }}</p>
            <p class="order-information"><span>Address: </span>{{ address.zipCode }}, {{ address.street }}, {{ address.city }}, {{ address.country }}</p>
            <h2>Order summary</h2>
            {% set total = null %}
            {% set totalPerItem = null %}
            {% set numberOfItems = null %}
            {% for item in cart %}
                {% if item.product %}
                    {% set total = total + (item.product.price * item.quantity) %}
                    {% set totalPerItem = item.product.price * item.quantity %}
                    {% set numberOfItems = numberOfItems + item.quantity %}
                    <div class="cart-item">
                        <a href="{{ path('app_product', { 'id': item.product.id }) }}" class="cart-anchor">
                            <img src="{{ item.product.image ? vich_uploader_asset(item.product, 'imageFile') : asset('assets/images/default.jpg') }}" alt="{{ item.product.title }}" width="100">
                        </a>
                        <p>{{ item.product.title }}</p>
                        <p>Qty: {{ item.quantity }}</p>
                        <p>${{ (totalPerItem / 100)|number_format(2, '.', ',') }}</p>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="cart-info">
                <span>Number of items: {{ numberOfItems }}</span>
                <span>Total: ${{ (total / 100)|number_format(2, '.', ',') }}</span>
            </div>
            <button type="submit" class="order-button">Checkout & Pay</button>
        {{ form_end(form) }}
    </main>
    <!-- MAIN END -->
{% endblock %}

templates/order/orders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    {% include 'partials/nav.html.twig' %}
    <!-- CANVAS -->
    <section class="canvas content">
        <h1>Orders</h1>
    </section>
    <!-- CANVAS END -->

    <!-- MAIN -->
    <main>
        {% if orders|length > 0 %}
            <div class="user-orders">
                {% set loopCount = null %}
                {% for order in orders %}
                    {% if order.status == 'Paid' or order.status == 'Delivered' or order.status == 'Cancelled' %}
                        {% set loopCount = loopCount + 1 %}
                        <div class="user-order">
                            <div class="user-order-number">{{ loopCount }}</div>
                            <div class="user-order-info">
                                <p><span class="red-span">Reference:</span> {{ order.reference }}</p>
                                <p><span class="red-span">Delivery address:</span> {{ order.deliveryAddress }}</p>
                                <p><span class="red-span">Ordered on:</span> {{ order.orderedOn|format_datetime('short', 'none') }}</p>
                                <p><span class="red-span">Total paid:</span> ${{ (order.total / 100)|number_format(2, '.', ',') }}</p>
                            </div>
                            <div  class="user-order-details">
                                <p><span class="red-span">Items</span></p>
                                <ul>
                                    {% for orderDetails in order.orderDetails %}
                                        <li>{{ orderDetails.quantity }}x {{ orderDetails.product }} at ${{ (orderDetails.price / 100)|number_format(2, '.', ',') }}/unit (${{ (orderDetails.totalPrice / 100)|number_format(2, '.', ',') }})</li>
                                    {% endfor %}
                                </ul>
                                <p><span class="red-span">Status:</span> {{ order.status }}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <div class="empty-cart">
                <p>You do not have any orders yet.</p>
                <a href="{{ path('app_products') }}" class="cart-button">Go to shop</a>
            </div>
        {% endif %}
    </main>
    <!-- MAIN END -->
{% endblock %}

templates/order/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    {% include 'partials/nav.html.twig' %}
    <!-- CANVAS -->
    <section class="canvas content">
        <h1>Order</h1>
    </section>
    <!-- CANVAS END -->

    <!-- MAIN -->
    <main>
        <div class="message-button">
            <h2 class="order-number">Your order number <span>{{ order.reference }}</span> has been placed.</h2>
            <a href="{{ path('app_orders') }}" class="cart-button">View your orders</a>
        </div>
    </main>
    <!-- MAIN END -->
{% endblock %}